from collections import Counter
import string as st
import os 
import sys
import math
import random

script_dir = os.path.dirname(__file__)
modulesPath = os.path.join(script_dir,"..","..","Test","Modules")
sys.path.append(modulesPath)

RED = "\033[91m"
BLUE = "\033[1;36m"
MAGENTA = "\033[1;35m"
GREEN = "\033[1;32m"
RESET = "\033[0m"

from cipherTools import chiSquared, ngrams # type: ignore

text = """
EAMYD KERRO THSMI GRHOW FYATI TOING RFHEA YOROM ASUIW CECON DTRNE THHAT IRETH NDTEE OFAYS ENSIL INCES OUCEY STRLA SAMES IGGEM AVHTH DIEIN EDCAT TYTHA ADOUH NGCHA OUEDY NDRMI UTABO AROUR GERAN TTMEN OCHED NTUME PRYOU DEOVI EXDIS METRE ROLYP INMIS DMGAN RTYPA SANER EEREK SENTO REEMO YOARE KEULI OBLYT LEEAB BTTOO MOAIN AMRES SIPLE MTFIA NVOCO EOINC RSTHE NVTOI THEST TWENI DBOUL ODEGO ROTOP ETVID WIHEM VITHE CEDEN HEOFT UEVAL HEOFT URIRP SECHA EHSOM HIAVE DTNTE THHAT ARERE HEEOT YSRWA TTTHA COHEY PRULD EDOCE ITBUT KIHIN GHTMI POTBE BLSSI DCEAN AIERT WONLY BEULD TEBET RYRFO FWOUI ULECO GODNE TETIA ETSOM GFHIN RAAVO TOBLE PAALL ESRTI OUOFC DMRSE EPAYB TILOT NONGA RCTHE SEOUR MAAND KEYTA EPSOM UAERS NTSIO MMOCO OOITT ROURP ALPOS YOBUT VEUHA URASS STEDU YOHAT VEUHA EISOM UENFL ONNCE DEHIS IOCIS NDNSA REIAM NGLYI OUONY ELTOH ALPSE DETHE OUALY ITRFA LFHFU NDRIE INMOL ARO
""".replace("\n","").replace(" ","")

print(ngrams().score(text))